FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json .

RUN npm ci

COPY . .

CMD ["npm", "run", "dev"]


# docker run --rm  -p 3000:3000 -v ./src:./app/src  --name $container_name $image_name