name: notes

services:
  notes-db:
    image: mongodb/mongodb-community-server:8.0.20-ubuntu2204
    ports:
      - 27018:27017
    env_file:
      - .env
    volumes:
      - type: volume
        source: notes-data
        target: /data/db
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
    networks:
      - notes-network

  notes-backend:
    depends_on:
      - notes-db
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - 4444:4444
    environment:
      - PORT=4444
      - MONGO_URI=mongodb://${DATABASE_USERNAME}:${DATABASE_PASSWORD}@notes-db/${DATABASE_NAME}
    networks:
      - notes-network
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src

volumes:
  notes-data:

networks:
  notes-network:
