services:
  notes-backend:
    environment:
      - NOTEBOOKS_BACKEND_URL=http://reverse-proxy/api/notebooks
    networks:
      - global-network

  notebooks-backend:
    networks:
      - global-network
