name: magmag
services:
  db:
    image: mongodb/mongodb-community-server:8.0.20-ubuntu2204
    ports:
      - 27017:27017
    env_file:
      - .env.db
    volumes:
      - type: bind
        source: ./db-config/mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
      - type: volume
        source: mongodb-data
        target: /data/db
    networks:
      - key-value-network
  backend:
    depends_on:
      - db
    build:
      context: ./back-end
      dockerfile: Dockerfile
    ports:
      - 5001:5000
    env_file:
      - .env.db
    networks:
      - key-value-network
    environment:
      - MONGO_HOST=db
      - PORT=5000
    volumes:
      - type: bind
        source: ./back-end/src
        target: /app/src
        read_only: true

volumes:
  mongodb-data:

networks:
  key-value-network:
