FROM node:22-alpine as dependencies

WORKDIR /app

COPY package*.json .

RUN npm ci

FROM gcr.io/distroless/nodejs22
WORKDIR /app

COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

ENV APP_NAME="Express App"

CMD ["index.js"]