FROM node:22-alpine AS build

WORKDIR /app

COPY package*.json .

RUN npm ci

COPY src src
COPY tsconfig.json tsconfig.json

RUN npm run build


FROM node:22-alpine AS dependencies
WORKDIR /app

COPY package*.json .

RUN npm ci --


FROM gcr.io/distroless/nodejs22
WORKDIR /app

COPY --from=dependencies /app/node_modules node_modules
COPY --from=build /app/dist dist

ENV APP_NAME="Express App (Multi-Stage Build)"

CMD ["dist/index.js"]