MONGO_IMAGE="mongodb/mongodb-community-server"
MONGO_VERSION="8.0.20-ubuntu2204"
CONTAINER_NAME="mongodb"

#ROOT CREDENTIALS
MONGO_ROOT_USERNAME="admin"
MONGO_ROOT_PASSWORD="password"

#KEY-VALUE CREDENTIALS
DATABASE_NAME="key-value-db"
MONGO_KEY_VALUE_USERNAME="key-value-user"
MONGO_KEY_VALUE_PASSWORD="key-value-password"

#CONNECTION STRING
LOCALHOST_PORT=27017
CONTAINER_PORT=27017
NETWORK_NAME="key-value-network"

#STORAGE
VOLUME_NAME="key-value-data"
VOLUME_CONTAINER_PATH="/data/db"


docker run -d \
--name $CONTAINER_NAME \
-e MONGO_INITDB_ROOT_USERNAME=$MONGO_ROOT_USERNAME \
-e MONGO_INITDB_ROOT_PASSWORD=$MONGO_ROOT_PASSWORD \
-e DATABASE_NAME=$DATABASE_NAME \
-e MONGO_KEY_VALUE_USERNAME=$MONGO_KEY_VALUE_USERNAME \
-e MONGO_KEY_VALUE_PASSWORD=$MONGO_KEY_VALUE_PASSWORD \
-p $LOCALHOST_PORT:$CONTAINER_PORT \
-v $VOLUME_NAME:$VOLUME_CONTAINER_PATH \
-v ./db-config/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro \
--network $NETWORK_NAME \
$MONGO_IMAGE:$MONGO_VERSION